import {
  ArrowLeft,
  BarChart2,
  Braces,
  Check,
  ChevronRight,
  Circle,
  Clock,
  Code,
  Copy,
  Crop,
  FileCheck,
  FileCode,
  FileText,
  Film,
  Folder,
  GitCompare,
  Grid,
  HardDrive,
  Hash,
  Image,
  Key,
  Layers,
  Loader2,
  Lock,
  Music,
  Palette,
  PenTool,
  Scissors,
  Search,
  Settings,
  Shapes,
  ShieldCheck,
  Sliders,
  Sparkles,
  Split,
  Star,
  Table,
  Terminal,
  TriangleAlert,
  Type,
  UploadCloud,
  Volume2,
  X
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

const ICONS: Record<string, LucideIcon> = {
  folder: Folder,
  'file-text': FileText,
  'file-code': FileCode,
  'file-check': FileCheck,
  image: Image,
  crop: Crop,
  film: Film,
  music: Music,
  braces: Braces,
  code: Code,
  sparkles: Sparkles,
  star: Star,
  clock: Clock,
  search: Search,
  settings: Settings,
  x: X,
  check: Check,
  copy: Copy,
  back: ArrowLeft,
  chevron: ChevronRight,
  upload: UploadCloud,
  alert: TriangleAlert,
  loader: Loader2,
  lock: Lock,
  'pen-tool': PenTool,
  shapes: Shapes,
  palette: Palette,
  scissors: Scissors,
  grid: Grid,
  hash: Hash,
  terminal: Terminal,
  'hard-drive': HardDrive,
  'shield-check': ShieldCheck,
  type: Type,
  volume: Volume2,
  sliders: Sliders,
  table: Table,
  key: Key,
  'bar-chart': BarChart2,
  'git-compare': GitCompare,
  split: Split,
  layers: Layers
}

/** Resolve a Lucide icon by name with a neutral fallback. */
export function getIcon(name: string): LucideIcon {
  return ICONS[name] ?? Circle
}
